server:
  port: ${PORT:8080}
springdoc:
  api-docs:
    enabled: true
logging:
  level:
    org:
    springframework: INFO
    root: INFO
    data:
      mongodb:
        core:
          MongoTemplate: INFO
spring:
  main:
    banner-mode: "off"
  application:
    name: library-management-ms
  profiles:
    active: local
  data:
    mongodb:
      uri: ${MONGO_URI}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "health"