server:
  port: 8080

logging:
  level:
    org.springframework:
      web:
        client:
          RestTemplate: debug

spring:
  main:
    banner-mode: "off"
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      ACCEPT_FLOAT_AS_INT: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/movie-crud
      database: movie-crud