server:
  port: ${port:8080}

logging:
  level:
    data:
      mongodb:
        core:
          MongoTemplate: DEBUG
        repository:
            Query: DEBUG

spring:
  main:
    banner-mode: "off"
  application:
    name: library-management
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      ACCEPT_FLOAT_AS_INT: false
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/ibrary-management
      database: library-management
