server:
  port: ${port:8080}

spring:
  main:
    banner-mode: "off"
  application:
    name: library-management-ms
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: library-management

logging:
  level:
    org:
    springframework: INFO
    web:
      socket:
        config:
          WebSocketMessageBrokerStats : INFO
    root: INFO
    data:
      mongodb:
        core:
           MongoTemplate: INFO

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "health"